apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-api-secrets
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: learn-external-secrets
