apiVersion: v1
kind: Service
metadata:
  name: userapi
  namespace: default
  labels:
    app: userapi
    service: userapi
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: userapi
